"""
db/models.py
------------
SQLAlchemy ORM models for Atlas Trading Agent.

All monetary values are stored as FLOAT (USD). Timestamps are UTC.
JSON columns use SQLAlchemy's JSON type which maps to TEXT on SQLite
and JSONB on PostgreSQL.
"""

from __future__ import annotations

import datetime
from typing import Any

from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    JSON,
    String,
    Text,
    func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Shared declarative base for all Atlas models."""


# ─────────────────────────────────────────────────────────────────────────────
#  Trade
# ─────────────────────────────────────────────────────────────────────────────


class Trade(Base):
    """
    A single completed trade (round-trip: entry + exit).

    ``agent_scores`` stores the conviction scores from each AI sub-agent
    at the time the signal was generated, e.g.::

        {"technical": 0.82, "sentiment": 0.61, "macro": 0.74}
    """

    __tablename__ = "trades"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Market identification
    symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    exchange: Mapped[str] = mapped_column(String(32), nullable=False, default="binance")

    # Order details
    side: Mapped[str] = mapped_column(String(8), nullable=False)  # "buy" | "sell"
    size: Mapped[float] = mapped_column(Float, nullable=False)    # Base asset quantity
    entry_price: Mapped[float] = mapped_column(Float, nullable=False)
    exit_price: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Calculated fields (populated on trade close)
    pnl: Mapped[float | None] = mapped_column(Float, nullable=True)
    pnl_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    fees: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Attribution
    strategy: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    mode: Mapped[str] = mapped_column(String(16), nullable=False, default="paper")  # "paper" | "live"

    # Timestamps (UTC)
    opened_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        server_default=func.now(),
    )
    closed_at: Mapped[datetime.datetime | None] = mapped_column(
        DateTime(timezone=False), nullable=True
    )

    # AI attribution
    agent_scores: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)

    # Exchange order IDs for reconciliation
    entry_order_id: Mapped[str | None] = mapped_column(String(128), nullable=True)
    exit_order_id: Mapped[str | None] = mapped_column(String(128), nullable=True)

    # Relationship: one trade can have many signals that led to it
    signals: Mapped[list["Signal"]] = relationship(
        "Signal", back_populates="trade", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return (
            f"<Trade id={self.id} {self.side.upper()} {self.symbol} "
            f"@ {self.entry_price} strategy={self.strategy}>"
        )


# ─────────────────────────────────────────────────────────────────────────────
#  Signal
# ─────────────────────────────────────────────────────────────────────────────


class Signal(Base):
    """
    A trading signal generated by one of the AI sub-agents.

    Signals may or may not be executed (filtered by risk controls,
    correlation guards, or drawdown limits).
    """

    __tablename__ = "signals"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    timestamp: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        server_default=func.now(),
        index=True,
    )
    symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    direction: Mapped[str] = mapped_column(String(8), nullable=False)  # "long" | "short" | "flat"
    conviction: Mapped[float] = mapped_column(Float, nullable=False)   # 0.0 – 1.0
    source_agent: Mapped[str] = mapped_column(String(64), nullable=False)
    strategy: Mapped[str] = mapped_column(String(64), nullable=False)

    # Execution outcome
    executed: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    skip_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Optional link to the trade that was opened on this signal
    trade_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("trades.id"), nullable=True, index=True
    )
    trade: Mapped["Trade | None"] = relationship("Trade", back_populates="signals")

    # Raw agent reasoning (truncated Claude response)
    reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)

    def __repr__(self) -> str:
        return (
            f"<Signal id={self.id} {self.direction.upper()} {self.symbol} "
            f"conviction={self.conviction:.2f} agent={self.source_agent}>"
        )


# ─────────────────────────────────────────────────────────────────────────────
#  AgentPerformance
# ─────────────────────────────────────────────────────────────────────────────


class AgentPerformance(Base):
    """
    Rolling performance metrics for each AI sub-agent.

    The engine adjusts each agent's ``weight`` based on historical
    Sharpe ratio and win rate, so better-performing agents have more
    influence over the ensemble decision.
    """

    __tablename__ = "agent_performance"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    agent_name: Mapped[str] = mapped_column(String(64), nullable=False, unique=True, index=True)

    # Dynamic weight (0.0 – 1.0, normalised across agents at runtime)
    weight: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)

    # Performance metrics (updated after every trade close)
    sharpe_ratio: Mapped[float | None] = mapped_column(Float, nullable=True)
    win_rate: Mapped[float | None] = mapped_column(Float, nullable=True)   # 0.0 – 1.0
    total_trades: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    total_pnl: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    avg_conviction: Mapped[float | None] = mapped_column(Float, nullable=True)

    last_updated: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    def __repr__(self) -> str:
        return (
            f"<AgentPerformance {self.agent_name} weight={self.weight:.3f} "
            f"win_rate={self.win_rate}>"
        )


# ─────────────────────────────────────────────────────────────────────────────
#  PortfolioSnapshot
# ─────────────────────────────────────────────────────────────────────────────


class PortfolioSnapshot(Base):
    """
    Point-in-time portfolio state snapshot.

    Captured by the heartbeat every 60 s in live/paper mode, and at
    the end of each backtest bar.

    ``positions_json`` format::

        [
            {"symbol": "BTC/USDT", "side": "long", "size": 0.05,
             "entry_price": 62000.0, "unrealized_pnl": 120.5},
            ...
        ]
    """

    __tablename__ = "portfolio_snapshots"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    timestamp: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        server_default=func.now(),
        index=True,
    )

    total_value: Mapped[float] = mapped_column(Float, nullable=False)
    available_balance: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    unrealized_pnl: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    realized_pnl_today: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Drawdown relative to the running equity peak (negative number)
    drawdown_pct: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    positions_json: Mapped[list[dict[str, Any]]] = mapped_column(JSON, nullable=False, default=list)

    mode: Mapped[str] = mapped_column(String(16), nullable=False, default="paper")

    def __repr__(self) -> str:
        return (
            f"<PortfolioSnapshot id={self.id} value={self.total_value:.2f} "
            f"drawdown={self.drawdown_pct:.2f}%>"
        )


# ─────────────────────────────────────────────────────────────────────────────
#  DailyPnL
# ─────────────────────────────────────────────────────────────────────────────


class DailyPnL(Base):
    """
    Aggregated daily P&L summary.

    One row per calendar date. Updated at end-of-day (UTC midnight)
    and after every trade close so the daily loss limit guard has
    a fast lookup.
    """

    __tablename__ = "daily_pnl"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    date: Mapped[datetime.date] = mapped_column(Date, nullable=False, unique=True, index=True)

    realized_pnl: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    unrealized_pnl: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    trades_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    wins: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    losses: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Peak intraday drawdown (most negative value seen during the day)
    max_drawdown: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Flags set by the risk engine
    daily_limit_hit: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    def __repr__(self) -> str:
        return (
            f"<DailyPnL date={self.date} realized={self.realized_pnl:.2f} "
            f"trades={self.trades_count}>"
        )


# ─────────────────────────────────────────────────────────────────────────────
#  NetWorthSnapshot
# ─────────────────────────────────────────────────────────────────────────────


class NetWorthSnapshot(Base):
    """
    Point-in-time net worth snapshot for CC.

    ``breakdown_json`` stores a category → value mapping, e.g.::

        {
            "Asset: Trading Portfolio": 8500.0,
            "Asset: TFSA": 14000.0,
            "Liability: Credit Card": 1200.0
        }
    """

    __tablename__ = "net_worth_snapshots"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    date: Mapped[datetime.date] = mapped_column(Date, nullable=False, index=True)

    total_assets: Mapped[float] = mapped_column(Float, nullable=False)
    total_liabilities: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    net_worth: Mapped[float] = mapped_column(Float, nullable=False)

    # Category → value breakdown (JSON)
    breakdown_json: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)

    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        server_default=func.now(),
    )

    def __repr__(self) -> str:
        return (
            f"<NetWorthSnapshot date={self.date} net_worth={self.net_worth:.2f}>"
        )


# ─────────────────────────────────────────────────────────────────────────────
#  TaxEvent
# ─────────────────────────────────────────────────────────────────────────────


class TaxEvent(Base):
    """
    A single taxable event for CRA reporting.

    ``event_type`` values:
    - "capital_gain"   : Realised capital gain from asset disposition
    - "capital_loss"   : Realised capital loss from asset disposition
    - "business_income": Income classified as business income (100% inclusion)
    - "tfsa_withdrawal": TFSA withdrawal (tax-free, tracked for room recovery)
    - "rrsp_contribution": RRSP contribution (creates tax deduction)
    """

    __tablename__ = "tax_events"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    date: Mapped[datetime.date] = mapped_column(Date, nullable=False, index=True)
    event_type: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    amount: Mapped[float] = mapped_column(Float, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    tax_year: Mapped[int] = mapped_column(Integer, nullable=False, index=True)

    # Optional link to the trade that generated this event
    trade_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("trades.id"), nullable=True, index=True
    )

    # Estimated tax impact in CAD (for planning purposes)
    tax_impact_estimate: Mapped[float | None] = mapped_column(Float, nullable=True)

    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        server_default=func.now(),
    )

    def __repr__(self) -> str:
        return (
            f"<TaxEvent date={self.date} type={self.event_type} "
            f"amount={self.amount:.2f} year={self.tax_year}>"
        )


# ─────────────────────────────────────────────────────────────────────────────
#  Expense
# ─────────────────────────────────────────────────────────────────────────────


class Expense(Base):
    """
    A personal or business expense for CC's budget tracking.

    ``category`` maps to ``finance.budget.ExpenseCategory`` values:
    Housing | Food | Transport | Business | Entertainment |
    Subscriptions | Savings | Investing | Other
    """

    __tablename__ = "expenses"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    date: Mapped[datetime.date] = mapped_column(Date, nullable=False, index=True)
    amount: Mapped[float] = mapped_column(Float, nullable=False)
    category: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    description: Mapped[str] = mapped_column(Text, nullable=False)

    # True when the expense is a deductible business expense
    is_business_deductible: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False
    )

    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        server_default=func.now(),
    )

    def __repr__(self) -> str:
        return (
            f"<Expense date={self.date} {self.category} ${self.amount:.2f} "
            f"'{self.description[:40]}'>"
        )


# ─────────────────────────────────────────────────────────────────────────────
#  FinancialGoal
# ─────────────────────────────────────────────────────────────────────────────


class FinancialGoal(Base):
    """
    A financial goal tracked over time.

    ``status`` values: "active" | "completed" | "paused" | "abandoned"

    Examples:
    - name="TFSA Maxed 2026", target=7000, current=2400, status="active"
    - name="Emergency Fund 6mo", target=13000, current=9200, status="active"
    - name="First Home Down Payment", target=80000, current=8000, status="active"
    """

    __tablename__ = "financial_goals"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    name: Mapped[str] = mapped_column(String(128), nullable=False)
    target_amount: Mapped[float] = mapped_column(Float, nullable=False)
    current_amount: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Optional target completion date for deadline-driven projections
    target_date: Mapped[datetime.date | None] = mapped_column(Date, nullable=True)

    status: Mapped[str] = mapped_column(
        String(16), nullable=False, default="active", index=True
    )

    # Notes or context for the goal
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    @property
    def progress_pct(self) -> float:
        """Percentage progress toward the goal (0.0–100.0)."""
        if self.target_amount <= 0:
            return 0.0
        return round(min(100.0, self.current_amount / self.target_amount * 100), 1)

    @property
    def remaining(self) -> float:
        """Amount still needed to reach the goal."""
        return max(0.0, self.target_amount - self.current_amount)

    def __repr__(self) -> str:
        return (
            f"<FinancialGoal '{self.name}' "
            f"{self.progress_pct:.1f}% "
            f"({self.current_amount:.0f}/{self.target_amount:.0f}) "
            f"status={self.status}>"
        )
