"""
db/models.py
------------
SQLAlchemy ORM models for Atlas Trading Agent.

All monetary values are stored as FLOAT (USD). Timestamps are UTC.
JSON columns use SQLAlchemy's JSON type which maps to TEXT on SQLite
and JSONB on PostgreSQL.
"""

from __future__ import annotations

import datetime
from typing import Any

from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    JSON,
    String,
    Text,
    func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Shared declarative base for all Atlas models."""


# ─────────────────────────────────────────────────────────────────────────────
#  Trade
# ─────────────────────────────────────────────────────────────────────────────


class Trade(Base):
    """
    A single completed trade (round-trip: entry + exit).

    ``agent_scores`` stores the conviction scores from each AI sub-agent
    at the time the signal was generated, e.g.::

        {"technical": 0.82, "sentiment": 0.61, "macro": 0.74}
    """

    __tablename__ = "trades"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Market identification
    symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    exchange: Mapped[str] = mapped_column(String(32), nullable=False, default="binance")

    # Order details
    side: Mapped[str] = mapped_column(String(8), nullable=False)  # "buy" | "sell"
    size: Mapped[float] = mapped_column(Float, nullable=False)    # Base asset quantity
    entry_price: Mapped[float] = mapped_column(Float, nullable=False)
    exit_price: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Calculated fields (populated on trade close)
    pnl: Mapped[float | None] = mapped_column(Float, nullable=True)
    pnl_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    fees: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Attribution
    strategy: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    mode: Mapped[str] = mapped_column(String(16), nullable=False, default="paper")  # "paper" | "live"

    # Timestamps (UTC)
    opened_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        server_default=func.now(),
    )
    closed_at: Mapped[datetime.datetime | None] = mapped_column(
        DateTime(timezone=False), nullable=True
    )

    # AI attribution
    agent_scores: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)

    # Exchange order IDs for reconciliation
    entry_order_id: Mapped[str | None] = mapped_column(String(128), nullable=True)
    exit_order_id: Mapped[str | None] = mapped_column(String(128), nullable=True)

    # Relationship: one trade can have many signals that led to it
    signals: Mapped[list["Signal"]] = relationship(
        "Signal", back_populates="trade", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return (
            f"<Trade id={self.id} {self.side.upper()} {self.symbol} "
            f"@ {self.entry_price} strategy={self.strategy}>"
        )


# ─────────────────────────────────────────────────────────────────────────────
#  Signal
# ─────────────────────────────────────────────────────────────────────────────


class Signal(Base):
    """
    A trading signal generated by one of the AI sub-agents.

    Signals may or may not be executed (filtered by risk controls,
    correlation guards, or drawdown limits).
    """

    __tablename__ = "signals"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    timestamp: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        server_default=func.now(),
        index=True,
    )
    symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    direction: Mapped[str] = mapped_column(String(8), nullable=False)  # "long" | "short" | "flat"
    conviction: Mapped[float] = mapped_column(Float, nullable=False)   # 0.0 – 1.0
    source_agent: Mapped[str] = mapped_column(String(64), nullable=False)
    strategy: Mapped[str] = mapped_column(String(64), nullable=False)

    # Execution outcome
    executed: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    skip_reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Optional link to the trade that was opened on this signal
    trade_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("trades.id"), nullable=True, index=True
    )
    trade: Mapped["Trade | None"] = relationship("Trade", back_populates="signals")

    # Raw agent reasoning (truncated Claude response)
    reasoning: Mapped[str | None] = mapped_column(Text, nullable=True)

    def __repr__(self) -> str:
        return (
            f"<Signal id={self.id} {self.direction.upper()} {self.symbol} "
            f"conviction={self.conviction:.2f} agent={self.source_agent}>"
        )


# ─────────────────────────────────────────────────────────────────────────────
#  AgentPerformance
# ─────────────────────────────────────────────────────────────────────────────


class AgentPerformance(Base):
    """
    Rolling performance metrics for each AI sub-agent.

    The engine adjusts each agent's ``weight`` based on historical
    Sharpe ratio and win rate, so better-performing agents have more
    influence over the ensemble decision.
    """

    __tablename__ = "agent_performance"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    agent_name: Mapped[str] = mapped_column(String(64), nullable=False, unique=True, index=True)

    # Dynamic weight (0.0 – 1.0, normalised across agents at runtime)
    weight: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)

    # Performance metrics (updated after every trade close)
    sharpe_ratio: Mapped[float | None] = mapped_column(Float, nullable=True)
    win_rate: Mapped[float | None] = mapped_column(Float, nullable=True)   # 0.0 – 1.0
    total_trades: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    total_pnl: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    avg_conviction: Mapped[float | None] = mapped_column(Float, nullable=True)

    last_updated: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    def __repr__(self) -> str:
        return (
            f"<AgentPerformance {self.agent_name} weight={self.weight:.3f} "
            f"win_rate={self.win_rate}>"
        )


# ─────────────────────────────────────────────────────────────────────────────
#  PortfolioSnapshot
# ─────────────────────────────────────────────────────────────────────────────


class PortfolioSnapshot(Base):
    """
    Point-in-time portfolio state snapshot.

    Captured by the heartbeat every 60 s in live/paper mode, and at
    the end of each backtest bar.

    ``positions_json`` format::

        [
            {"symbol": "BTC/USDT", "side": "long", "size": 0.05,
             "entry_price": 62000.0, "unrealized_pnl": 120.5},
            ...
        ]
    """

    __tablename__ = "portfolio_snapshots"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    timestamp: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=False),
        nullable=False,
        server_default=func.now(),
        index=True,
    )

    total_value: Mapped[float] = mapped_column(Float, nullable=False)
    available_balance: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    unrealized_pnl: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    realized_pnl_today: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Drawdown relative to the running equity peak (negative number)
    drawdown_pct: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    positions_json: Mapped[list[dict[str, Any]]] = mapped_column(JSON, nullable=False, default=list)

    mode: Mapped[str] = mapped_column(String(16), nullable=False, default="paper")

    def __repr__(self) -> str:
        return (
            f"<PortfolioSnapshot id={self.id} value={self.total_value:.2f} "
            f"drawdown={self.drawdown_pct:.2f}%>"
        )


# ─────────────────────────────────────────────────────────────────────────────
#  DailyPnL
# ─────────────────────────────────────────────────────────────────────────────


class DailyPnL(Base):
    """
    Aggregated daily P&L summary.

    One row per calendar date. Updated at end-of-day (UTC midnight)
    and after every trade close so the daily loss limit guard has
    a fast lookup.
    """

    __tablename__ = "daily_pnl"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    date: Mapped[datetime.date] = mapped_column(Date, nullable=False, unique=True, index=True)

    realized_pnl: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    unrealized_pnl: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    trades_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    wins: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    losses: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    # Peak intraday drawdown (most negative value seen during the day)
    max_drawdown: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)

    # Flags set by the risk engine
    daily_limit_hit: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    def __repr__(self) -> str:
        return (
            f"<DailyPnL date={self.date} realized={self.realized_pnl:.2f} "
            f"trades={self.trades_count}>"
        )
