"""
scripts/validate_memory.py
--------------------------
Memory hygiene + auto-index.

Why: CC asked "is there a better way to orchestrate this data?" — the answer
is: keep markdown (human-readable, git-diffable, works across all AI
runtimes), but enforce frontmatter consistency and regenerate the index so
MEMORY.md never drifts from the actual files.

This script:
  1. Validates every memory/*.md file has valid YAML frontmatter with
     `name`, `description`, and `type` (one of: user, feedback, project, reference).
  2. Flags files older than 90 days as "stale" — likely safe to review.
  3. Regenerates MEMORY.md index from discovered files, grouped by type.

Usage:
  python scripts/validate_memory.py              # lint + regenerate index
  python scripts/validate_memory.py --check      # exit 1 if any file is broken
                                                  # (for CI / pre-commit hooks)
  python scripts/validate_memory.py --quiet      # suppress per-file output
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from datetime import date, datetime
from pathlib import Path
from typing import Any


def _resolve_memory_root() -> Path:
    """Memory root is per-machine. Override via ATLAS_MEMORY_ROOT in .env.agents.

    Why: auto-memory lives outside the repo at a Claude-Code-managed path
    that differs by OS + install path. Hardcoding the Windows path broke
    validation on Conaugh's Mac twin.
    """
    override = os.environ.get("ATLAS_MEMORY_ROOT")
    if override:
        return Path(override).expanduser()
    # Fallbacks by platform — Windows default first, then Mac default.
    candidates = [
        Path(r"C:\Users\User\.claude\projects\c--Users-User-APPS-CFO-Agent\memory"),
        Path.home() / ".claude" / "projects" / "-Users-conaugh-Desktop-CFO-Agent" / "memory",
    ]
    for cand in candidates:
        if cand.exists():
            return cand
    return candidates[0]


_MEMORY_ROOT = _resolve_memory_root()
_STALE_DAYS = 90
_VALID_TYPES = {"user", "feedback", "project", "reference"}


def _parse_frontmatter(text: str) -> dict[str, Any]:
    """Lenient YAML-ish parse — same shape as build_capabilities.py."""
    if not text.startswith("---"):
        return {}
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}
    fm_block = parts[1].strip()
    result: dict[str, Any] = {}
    for line in fm_block.splitlines():
        if not line.strip() or ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        if val.startswith("[") and val.endswith("]"):
            val = [x.strip() for x in val[1:-1].split(",") if x.strip()]
        result[key] = val
    return result


def _file_age_days(path: Path) -> int:
    return (datetime.now() - datetime.fromtimestamp(path.stat().st_mtime)).days


def validate_file(path: Path) -> tuple[bool, list[str], dict]:
    """Return (ok, issues, frontmatter)."""
    issues: list[str] = []
    try:
        text = path.read_text(encoding="utf-8")
    except Exception as exc:
        return False, [f"unreadable: {exc}"], {}

    fm = _parse_frontmatter(text)
    if not fm:
        issues.append("missing frontmatter (file must start with --- ... ---)")
        return False, issues, {}

    for required in ("name", "description", "type"):
        if not fm.get(required):
            issues.append(f"missing required field: {required}")

    t = fm.get("type", "")
    if t and t not in _VALID_TYPES:
        issues.append(f"invalid type {t!r}; must be one of {sorted(_VALID_TYPES)}")

    desc = fm.get("description", "")
    if desc and len(desc) < 20:
        issues.append(f"description too short ({len(desc)} chars); aim for >= 40")

    body = text.split("---", 2)[-1].strip()
    if len(body) < 50:
        issues.append(f"body too short ({len(body)} chars); add why + how to apply")

    return not issues, issues, fm


def regenerate_index(files: list[tuple[Path, dict]]) -> str:
    """Build MEMORY.md from validated files, grouped by type."""
    by_type: dict[str, list[tuple[Path, dict]]] = {t: [] for t in _VALID_TYPES}
    for path, fm in files:
        t = fm.get("type", "feedback")
        by_type.setdefault(t, []).append((path, fm))

    lines = [
        "# ATLAS Memory System (CFO-Agent)",
        "",
        f"> **Auto-generated index** — regenerated by `scripts/validate_memory.py`. "
        f"Last built: {date.today().isoformat()}. Do not edit by hand; add a new file and rerun.",
        "",
        f"{len(files)} memory files | "
        + ", ".join(f"{len(by_type.get(t, []))} {t}" for t in sorted(_VALID_TYPES) if by_type.get(t)),
        "",
    ]

    headings = {
        "user": "## User Profile",
        "project": "## Project Status",
        "reference": "## References",
        "feedback": "## Feedback — Behavior",
    }

    for t in ("user", "project", "reference", "feedback"):
        items = by_type.get(t, [])
        if not items:
            continue
        lines.append(headings.get(t, f"## {t.title()}"))
        # Sort: pin anything whose name starts with "CRITICAL" or "#1" to top,
        # otherwise alphabetize by name
        def sort_key(entry: tuple[Path, dict]) -> tuple[int, str]:
            name = entry[1].get("name", entry[0].stem)
            priority = 0 if re.match(r"(CRITICAL|#1|MANDATORY)", name, re.IGNORECASE) else 1
            return (priority, name.lower())
        items.sort(key=sort_key)
        for path, fm in items:
            name = fm.get("name", path.stem)
            desc = fm.get("description", "").strip()
            # Truncate to keep lines under 150 chars
            if len(desc) > 100:
                desc = desc[:97] + "…"
            age = _file_age_days(path)
            stale_mark = "  [STALE]stale" if age > _STALE_DAYS else ""
            lines.append(f"- [{name}]({path.name}) — {desc}{stale_mark}")
        lines.append("")

    lines.extend([
        "## Brain (authoritative, lives in repo)",
        "",
        "`c:\\Users\\User\\APPS\\CFO-Agent\\brain\\`:",
        "- CLAUDE.md, AGENTS.md, GEMINI.md — identity files per AI runtime",
        "- USER.md, SOUL.md, STATE.md, HEARTBEAT.md, DASHBOARD.md",
        "- **CAPABILITIES.md** — auto-generated registry of everything Atlas can do "
        "(regenerated by `scripts/build_capabilities.py`)",
        "- **AGENT_ORCHESTRATION.md** — CFO ↔ CEO contract + 4-runtime unification",
        "- TAX_PLAYBOOK_INDEX.md — entry to the 59-doc tax library",
        "",
        "## Archived (trading-era, frozen)",
        "",
        "`C:\\Users\\User\\.claude\\projects\\c--Users-User-APPS-trading-agent\\memory\\` — "
        "20 trading-era feedback + reference files kept as archive in case the "
        "algo trading engine is ever revived. Not loaded into active sessions.",
    ])

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 on any validation error. No file writes.")
    parser.add_argument("--quiet", action="store_true", help="Suppress per-file output.")
    args = parser.parse_args()

    if not _MEMORY_ROOT.exists():
        print(f"[memory] root not found: {_MEMORY_ROOT}")
        return 1

    # Skip MEMORY.md (auto-generated index) plus the self-improvement-protocol
    # artifacts (MISTAKES.md, PATTERNS.md, CAPABILITY_GAPS.md). Those use a
    # different schema (tags + created + originSessionId) and are owned by
    # skills/self-improvement-protocol — not by this validator.
    _SKIP = {"MEMORY.md", "MISTAKES.md", "PATTERNS.md", "CAPABILITY_GAPS.md"}
    files = sorted(p for p in _MEMORY_ROOT.glob("*.md") if p.name not in _SKIP)
    problems = 0
    valid_files: list[tuple[Path, dict]] = []

    for path in files:
        ok, issues, fm = validate_file(path)
        age = _file_age_days(path)
        if ok:
            valid_files.append((path, fm))
            if not args.quiet:
                stale = " ([STALE] STALE)" if age > _STALE_DAYS else ""
                print(f"  [ok] {path.name:<40} [{fm.get('type'):<9}] {age}d old{stale}")
        else:
            problems += 1
            print(f"  [FAIL]{path.name}")
            for issue in issues:
                print(f"       -> {issue}")

    if args.check:
        if problems:
            print(f"\n{problems} memory file(s) failed validation — fix before committing.")
            return 1
        print(f"\nAll {len(valid_files)} memory files valid.")
        return 0

    # Regenerate index
    index_text = regenerate_index(valid_files)
    index_path = _MEMORY_ROOT / "MEMORY.md"
    index_path.write_text(index_text, encoding="utf-8")
    print(
        f"\n[memory] regenerated {index_path.name} — "
        f"{len(valid_files)} entries indexed, {problems} errors"
    )
    return 0 if not problems else 1


if __name__ == "__main__":
    sys.exit(main())
